name: Docker Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gamebackend:latest
        host: http://157.230.56.58/
        username: root
        password: Emc_1486374269_Emc
        script: |
          docker stop gamebackend || true
          docker rm gamebackend || true
          docker pull boaufort/gamebackend:latest
          docker run -p 8096:8096 --name gamebackend -d boaufort/gamebackend:latest
