name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd gamebackend/gamebackend
          git pull
          docker stop gamebackend-container
          docker rm gamebackend-container
          docker rmi gamebackend -f # Eski imajı sil
          docker build -t gamebackend . --rm # Yeni imajı oluştur ve intermediate containerları sil
          docker run -d -p 8096:8096 --name gamebackend-container gamebackend
